"""
Generate investigation-style memos with charts, caveats, and follow-up
recommendations for suspect lots.
"""

import pandas as pd
import yaml
from pathlib import Path
from datetime import datetime
from jinja2 import Template


_CONFIG_PATH = Path(__file__).resolve().parents[2] / "configs" / "spec_limits.yml"

_MEMO_TEMPLATE = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{{ title }}</title>
<style>
body { font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }
h1 { color: #1a3a5c; border-bottom: 2px solid #1a3a5c; padding-bottom: 8px; }
h2 { color: #2c5f8a; margin-top: 30px; }
table { border-collapse: collapse; width: 100%; margin: 15px 0; }
th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }
th { background: #f0f4f8; }
.caveat { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin: 15px 0; }
.evidence { background: #f8f9fa; border-left: 4px solid #28a745; padding: 12px; margin: 15px 0; }
.footer { margin-top: 40px; font-size: 0.85em; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }
</style></head>
<body>
<h1>{{ title }}</h1>
<p><strong>Generated:</strong> {{ timestamp }}</p>
<p><strong>Response variable:</strong> {{ response_var }}</p>

<h2>1. Event Summary</h2>
<p>Lot <strong>{{ lot_id }}</strong> was flagged as suspect with reason code: <em>{{ reason_code }}</em> (severity: {{ severity }}).</p>
<p>Observed {{ response_var }}: <strong>{{ suspect_value }}</strong> (spec: {{ lsl }}–{{ usl }}).</p>

<h2>2. Comparison Set</h2>
<p>{{ peer_count }} peer lots matched on: {{ matching_keys }}.</p>
{% if low_peer_warning %}
<div class="caveat">{{ caveat_low_peers }}</div>
{% endif %}

<h2>3. Statistical Evidence</h2>
<div class="evidence">
<p>Top features with largest standardized differences between the suspect lot and its peer group:</p>
</div>
{{ comparison_table }}

<h2>4. Candidate Contributors</h2>
<p>Features ranked by association strength from the primary interpretable model (logistic regression).</p>
{{ contributor_table }}
<div class="caveat">{{ caveat_model }}</div>

<h2>5. Recommended Follow-Up</h2>
<ul>
{% for item in followup_items %}
<li>{{ item }}</li>
{% endfor %}
</ul>

<div class="footer">
<p>This memo reflects statistical association and is not a determination of root cause.
Process-level review by qualified personnel is required before attributing causality.
Generated by the OOT Investigation Workbench.</p>
</div>
</body></html>
"""


def _load_config() -> dict:
    with open(_CONFIG_PATH) as f:
        return yaml.safe_load(f)


def generate_investigation_report(
    lot_id: str,
    suspect_row: pd.Series,
    peer_metadata: dict,
    comparisons: pd.DataFrame,
    contributors: pd.DataFrame,
    response_var: str = "dissolution",
    config: dict | None = None,
    output_path: Path | None = None,
) -> str:
    """Generate an HTML investigation memo for a suspect lot.

    Returns the rendered HTML string and optionally writes to output_path.
    """
    if config is None:
        config = _load_config()

    var_cfg = config["response_variables"][response_var]
    memo_cfg = config["investigation_memo"]

    # Build comparison table HTML
    top_comp = comparisons.head(8)
    comp_html = top_comp.to_html(index=False, classes="comparison", float_format="%.3f")

    # Build contributor table HTML
    top_contrib = contributors.head(8)
    contrib_cols = [c for c in ["rank", "feature", "coefficient", "interpretation"] if c in top_contrib.columns]
    contrib_html = top_contrib[contrib_cols].to_html(index=False, classes="contributors")

    # Follow-up items based on top contributors
    followup = []
    for _, row in contributors.head(3).iterrows():
        feat = row["feature"]
        followup.append(f"Review process records for {feat} on lot {lot_id} and compare to peer range.")
    followup.append("Confirm raw material COA data for the suspect lot against supplier specifications.")
    followup.append("Assess whether any equipment or environmental deviations were logged during manufacture.")

    template = Template(_MEMO_TEMPLATE)
    html = template.render(
        title=memo_cfg["title_template"].format(lot_id=lot_id),
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
        response_var=response_var,
        lot_id=lot_id,
        reason_code=suspect_row.get("reason_code", "N/A"),
        severity=suspect_row.get("severity", "N/A"),
        suspect_value=round(float(suspect_row[response_var]), 2),
        lsl=var_cfg["lower_spec"],
        usl=var_cfg["upper_spec"],
        peer_count=peer_metadata["peer_count"],
        matching_keys=", ".join(peer_metadata["matching_keys_used"]),
        low_peer_warning=peer_metadata.get("low_peer_warning", False),
        caveat_low_peers=memo_cfg["caveat_low_peers"].format(
            threshold=config["peer_matching"]["low_peer_warning_threshold"]
        ),
        comparison_table=comp_html,
        contributor_table=contrib_html,
        caveat_model=memo_cfg["caveat_model"],
        followup_items=followup,
    )

    if output_path is not None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")

    return html
